### ISSUE TITLE
No IPv6 support for www.chef.io

### ISSUE THREAD

**Issue by funzoneq** [chef-cookbooks/omnibus_updater#121]
On a host with IPv6 connectivity only, running this cookbook:

```
Errno::ENETUNREACH
------------------
Network is unreachable - connect(2) for "www.chef.io" port 80

Cookbook Trace:
---------------
  /var/chef/cache/cookbooks/omnibus_updater/libraries/omnitrucker.rb:95:in `url'
  /var/chef/cache/cookbooks/omnibus_updater/recipes/downloader.rb:27:in `from_file'
  /var/chef/cache/cookbooks/omnibus_updater/recipes/default.rb:27:in `from_file'

Relevant File Content:
----------------------
/var/chef/cache/cookbooks/omnibus_updater/libraries/omnitrucker.rb:

 88:          url = build_url(url_or_node)
 89:          node = url_or_node
 90:        else
 91:          url = url_or_node
 92:          raise "Node instance is required for Omnitruck.url!" unless node
 93:        end
 94:        request = Chef::REST::RESTRequest.new(:head, URI.parse(url), nil)
 95>>       result = request.call
 96:        if(result.kind_of?(Net::HTTPRedirection))
 97:          result['location']
 98:        end
 99:      end
100:
101:    end
102:  end
103:

Platform:
---------
x86_64-linux
```

Please request Fastly to enable IPv6 for your setup:

```
dig AAAA www.chef.io +short
g.global-ssl.fastly.net.
prod.g.ssl.global.fastlylb.net.
```

**Comment by tas50** [comment]
I've moved this over to the feedback site to get it on our product teams radar. I'm told there's more to it than just the Fastly side.

https://feedback.chef.io/forums/301644-chef-product-feedback/suggestions/17527759-support-ipv6-on-chef-io
