### ISSUE TITLE
chef-client service fails to restart

### ISSUE THREAD

**Issue by jayaich** [chef-cookbooks/omnibus_updater#59]
Yesterday our chef nodes updated the chef-client to version 11.14.6 via omnibus_updater. Unfortunately the chef-client service did not restart, so we had to manually restart them all this morning. (The same thing happened at the last upgrade as well.)

Each node has the 'restart_chef_service' attribute set to true.
## The chef-client log shows:

[2014-08-18T19:45:02+01:00] INFO: remote_file[omnibus_remote[chef_11.14.6-1_amd64.deb]] sending create action to ruby_block[Omnibus Chef install notifier](immediate)
[2014-08-18T19:45:02+01:00] INFO: Processing ruby_block[Omnibus Chef install notifier] action create (omnibus_updater::installer line 39)
[2014-08-18T19:45:02+01:00] INFO: ruby_block[Omnibus Chef install notifier] called
[2014-08-18T19:45:02+01:00] INFO: Processing file[/tmp/nocheck] action create (omnibus_updater::installer line 4)
[2014-08-18T19:45:02+01:00] INFO: Processing ruby_block[omnibus chef killer] action nothing (omnibus_updater::installer line 9)
[2014-08-18T19:45:02+01:00] INFO: Processing execute[omnibus_install[chef_11.14.6-1_amd64.deb]] action nothing (omnibus_updater::installer line 19)
[2014-08-18T19:45:02+01:00] INFO: Processing ruby_block[Omnibus Chef install notifier] action nothing (omnibus_updater::installer line 39)
[2014-08-18T19:45:02+01:00] INFO: ruby_block[Omnibus Chef install notifier] sending run action to execute[omnibus_install[chef_11.14.6-1_amd64.deb]](delayed)
[2014-08-18T19:45:02+01:00] INFO: Processing execute[omnibus_install[chef_11.14.6-1_amd64.deb]] action run (omnibus_updater::installer line 19)
[2014-08-18T19:45:06+01:00] INFO: execute[omnibus_install[chef_11.14.6-1_amd64.deb]] ran successfully
[2014-08-18T19:45:06+01:00] INFO: execute[omnibus_install[chef_11.14.6-1_amd64.deb]] sending restart action to service[chef-client](immediate)
[2014-08-18T19:45:06+01:00] INFO: Processing service[chef-client] action restart (chef-client::init_service line 32)
[2014-08-18T19:45:06+01:00] INFO: SIGTERM received, exiting gracefully
[2014-08-18T19:45:13+01:00] FATAL: Chef is already running pid 30348
[2014-08-18T19:45:13+01:00] INFO: service[chef-client] restarted
[2014-08-18T19:45:13+01:00] INFO: execute[omnibus_install[chef_11.14.6-1_amd64.deb]] sending create action to ruby_block[omnibus chef killer](immediate)
[2014-08-18T19:45:13+01:00] INFO: Processing ruby_block[omnibus chef killer] action create (omnibus_updater::installer line 9)
[2014-08-18T19:45:13+01:00] ERROR: Running exception handlers
[2014-08-18T19:45:13+01:00] ERROR: Exception handlers complete
[2014-08-18T19:45:13+01:00] FATAL: Stacktrace dumped to /var/chef/cache/chef-stacktrace.out
[2014-08-18T19:45:13+01:00] INFO: Sending resource update report (run-id: 522dd13d-ffba-455b-b3d0-fb9d839166a6)
## [2014-08-18T19:45:14+01:00] ERROR: ruby_block[omnibus chef killer](omnibus_updater::installer line 9) had an error: RuntimeError: New omnibus chef version installed. Killing Chef run!

The stack trace shows:

---

Generated at 2014-08-18 19:45:13 +0100
RuntimeError: ruby_block[omnibus chef killer](omnibus_updater::installer line 9) had an error: RuntimeError: New omnibus chef version installed. Killing Chef run!
/var/chef/cache/cookbooks/omnibus_updater/recipes/installer.rb:11:in 'block (2 levels) in from_file'
/opt/chef/embedded/lib/ruby/gems/1.9.1/gems/chef-11.14.2/lib/chef/provider/ruby_block.rb:33:in 'call'
/opt/chef/embedded/lib/ruby/gems/1.9.1/gems/chef-11.14.2/lib/chef/provider/ruby_block.rb:33:in 'block in action_run'
/opt/chef/embedded/lib/ruby/gems/1.9.1/gems/chef-11.14.2/lib/chef/mixin/why_run.rb:52:in 'call'
/opt/chef/embedded/lib/ruby/gems/1.9.1/gems/chef-11.14.2/lib/chef/mixin/why_run.rb:52:in 'add_action'
/opt/chef/embedded/lib/ruby/gems/1.9.1/gems/chef-11.14.2/lib/chef/provider.rb:156:in 'converge_by'
/opt/chef/embedded/lib/ruby/gems/1.9.1/gems/chef-11.14.2/lib/chef/provider/ruby_block.rb:32:in 'action_run'
/opt/chef/embedded/lib/ruby/gems/1.9.1/gems/chef-11.14.2/lib/chef/provider.rb:121:in 'run_action'
/opt/chef/embedded/lib/ruby/gems/1.9.1/gems/chef-11.14.2/lib/chef/resource.rb:648:in 'run_action'
/opt/chef/embedded/lib/ruby/gems/1.9.1/gems/chef-11.14.2/lib/chef/runner.rb:49:in 'run_action'
/opt/chef/embedded/lib/ruby/gems/1.9.1/gems/chef-11.14.2/lib/chef/runner.rb:57:in 'block in run_action'
/opt/chef/embedded/lib/ruby/gems/1.9.1/gems/chef-11.14.2/lib/chef/runner.rb:55:in 'each'
/opt/chef/embedded/lib/ruby/gems/1.9.1/gems/chef-11.14.2/lib/chef/runner.rb:55:in 'run_action'
/opt/chef/embedded/lib/ruby/gems/1.9.1/gems/chef-11.14.2/lib/chef/runner.rb:111:in 'run_delayed_notification'
/opt/chef/embedded/lib/ruby/gems/1.9.1/gems/chef-11.14.2/lib/chef/runner.rb:99:in 'block in run_delayed_notifications'
/opt/chef/embedded/lib/ruby/gems/1.9.1/gems/chef-11.14.2/lib/chef/runner.rb:98:in 'each'
/opt/chef/embedded/lib/ruby/gems/1.9.1/gems/chef-11.14.2/lib/chef/runner.rb:98:in 'run_delayed_notifications'
/opt/chef/embedded/lib/ruby/gems/1.9.1/gems/chef-11.14.2/lib/chef/runner.rb:88:in 'converge'
/opt/chef/embedded/lib/ruby/gems/1.9.1/gems/chef-11.14.2/lib/chef/client.rb:345:in 'converge'
/opt/chef/embedded/lib/ruby/gems/1.9.1/gems/chef-11.14.2/lib/chef/client.rb:431:in 'do_run'
/opt/chef/embedded/lib/ruby/gems/1.9.1/gems/chef-11.14.2/lib/chef/client.rb:213:in 'block in run'
/opt/chef/embedded/lib/ruby/gems/1.9.1/gems/chef-11.14.2/lib/chef/client.rb:207:in 'fork'
/opt/chef/embedded/lib/ruby/gems/1.9.1/gems/chef-11.14.2/lib/chef/client.rb:207:in 'run'
/opt/chef/embedded/lib/ruby/gems/1.9.1/gems/chef-11.14.2/lib/chef/application.rb:237:in 'run_chef_client'
/opt/chef/embedded/lib/ruby/gems/1.9.1/gems/chef-11.14.2/lib/chef/application/client.rb:338:in 'block in run_application'
/opt/chef/embedded/lib/ruby/gems/1.9.1/gems/chef-11.14.2/lib/chef/application/client.rb:327:in 'loop'
/opt/chef/embedded/lib/ruby/gems/1.9.1/gems/chef-11.14.2/lib/chef/application/client.rb:327:in 'run_application'
/opt/chef/embedded/lib/ruby/gems/1.9.1/gems/chef-11.14.2/lib/chef/application.rb:55:in 'run'
/opt/chef/embedded/lib/ruby/gems/1.9.1/gems/chef-11.14.2/bin/chef-client:26:in '<top (required)>'
/usr/bin/chef-client:23:in 'load'

**Comment by jmreicha** [comment]
@jayaich This looks a little bit dated but did you ever find a solution for this?  I am running in to the same issue.

**Comment by jayaich** [comment]
I cannot say that I 'looked' for a solution. I simply reported the problem as happening because the 'restart_chef_service' attribute doesn't seem to be doing its job. The problem has happened each time chef-client has been updated (as happened very recently).

**Comment by isavcic** [comment]
My solution was to add something like this to /etc/cron.d/chef-client-check:
```
*/10 * * * * root /usr/bin/killall -0 chef-client >/dev/null 2>&1 || /sbin/service chef-client start >/dev/null 2>&1
*/10 * * * * root /usr/bin/find /var/log/chef/client.log -mmin +180 -exec /sbin/service chef-client restart >/dev/null 2>&1 \;
```

This will catch when chef-client died completely or stopped functioning.

**Comment by pluesch0r** [comment]
i changed the service definition in installer.rb to the following:

<pre>
service 'chef-client' do
  action :nothing
  restart_command 'service chef-client restart &'
end
</pre>

Does anyone else care to test if they are happy with this/if it's working? If so, I'd submit a pull request.

**Comment by bdwyertech** [comment]
Maybe we should have this on the service definition.
https://github.com/chef-cookbooks/chef-client/blob/master/recipes/init_service.rb#L33

**Comment by tas50** [comment]
Closing this out since it appears that @bdwyertech fixed it
