### ISSUE TITLE
ipv6 issues with www.opscode.com

### ISSUE THREAD

**Issue by chr4** [chef-cookbooks/omnibus_updater#91]
Downloading the Omnibus installer doesn't work on ipv6 only connections.

```
SocketError
-----------
getaddrinfo: Name or service not known

Cookbook Trace:
---------------
  /var/chef/cache/cookbooks/omnibus_updater/libraries/omnitrucker.rb:85:in `url'
  /var/chef/cache/cookbooks/omnibus_updater/recipes/downloader.rb:27:in `from_file'
  /var/chef/cache/cookbooks/omnibus_updater/recipes/default.rb:25:in `from_file'

Relevant File Content:
----------------------
/var/chef/cache/cookbooks/omnibus_updater/libraries/omnitrucker.rb:

 78:          url = build_url(url_or_node)
 79:          node = url_or_node
 80:        else
 81:          url = url_or_node
 82:          raise "Node instance is required for Omnitruck.url!" unless node
 83:        end
 84:        request = Chef::REST::RESTRequest.new(:head, URI.parse(url), nil)
 85>>       result = request.call
 86:        if(result.kind_of?(Net::HTTPRedirection))
 87:          result['location']
 88:        end
 89:      end
 90:
 91:    end
 92:  end
 93:
```

The underlying problem is probably, that the `www.opscode.com` DNS entry is a `CNAME` record, with no `AAAA` attached, resulting in some sort of resolving problem.

``` shell
dig +short AAAA www.opscode.com
ocfrontend-elb-202116047.us-west-2.elb.amazonaws.com.
```

curl can handle resolving just fine (falls back to ipv4, which I setup a NAT for)

``` bash
ipv6 ~ % curl -v -I www.opscode.com
* Rebuilt URL to: www.opscode.com/
* Hostname was NOT found in DNS cache
*   Trying 54.186.31.111...
* Connected to www.opscode.com (54.186.31.111) port 80 (#0)
> HEAD / HTTP/1.1
> User-Agent: curl/7.35.0
> Host: www.opscode.com
> Accept: */*
```

```
```

**Comment by chr4** [comment]
This might even be more complicated. I encounter the same issue on a dual-stack host when using the ipv6 addresses of the nameservers. As soon as I change `/etc/resolv.conf` to use the same nameservers ipv4 addresses, it works.

Wild guess: Might be related to https://bugzilla.redhat.com/show_bug.cgi?id=804630

**Comment by iennae** [comment]
@chr4 This appears to have been fixed as of https://github.com/chef-cookbooks/omnibus_updater/pull/89/files. If this is still a problem please reopen. Thanks!
